# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Codes/c/sdl2_engine_opengl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Codes/c/sdl2_engine_opengl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Codes/c/sdl2_engine_opengl/CMakeFiles /home/user/Codes/c/sdl2_engine_opengl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Codes/c/sdl2_engine_opengl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project

# Build rule for target.
project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 project
.PHONY : project

# fast build rule for target.
project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/build
.PHONY : project/fast

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Game.cpp.s
.PHONY : Game.cpp.s

engine/core/Camera.o: engine/core/Camera.cpp.o

.PHONY : engine/core/Camera.o

# target to build an object file
engine/core/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/Camera.cpp.o
.PHONY : engine/core/Camera.cpp.o

engine/core/Camera.i: engine/core/Camera.cpp.i

.PHONY : engine/core/Camera.i

# target to preprocess a source file
engine/core/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/Camera.cpp.i
.PHONY : engine/core/Camera.cpp.i

engine/core/Camera.s: engine/core/Camera.cpp.s

.PHONY : engine/core/Camera.s

# target to generate assembly for a file
engine/core/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/Camera.cpp.s
.PHONY : engine/core/Camera.cpp.s

engine/core/Engine.o: engine/core/Engine.cpp.o

.PHONY : engine/core/Engine.o

# target to build an object file
engine/core/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/Engine.cpp.o
.PHONY : engine/core/Engine.cpp.o

engine/core/Engine.i: engine/core/Engine.cpp.i

.PHONY : engine/core/Engine.i

# target to preprocess a source file
engine/core/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/Engine.cpp.i
.PHONY : engine/core/Engine.cpp.i

engine/core/Engine.s: engine/core/Engine.cpp.s

.PHONY : engine/core/Engine.s

# target to generate assembly for a file
engine/core/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/Engine.cpp.s
.PHONY : engine/core/Engine.cpp.s

engine/core/EntityManager.o: engine/core/EntityManager.cpp.o

.PHONY : engine/core/EntityManager.o

# target to build an object file
engine/core/EntityManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/EntityManager.cpp.o
.PHONY : engine/core/EntityManager.cpp.o

engine/core/EntityManager.i: engine/core/EntityManager.cpp.i

.PHONY : engine/core/EntityManager.i

# target to preprocess a source file
engine/core/EntityManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/EntityManager.cpp.i
.PHONY : engine/core/EntityManager.cpp.i

engine/core/EntityManager.s: engine/core/EntityManager.cpp.s

.PHONY : engine/core/EntityManager.s

# target to generate assembly for a file
engine/core/EntityManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/EntityManager.cpp.s
.PHONY : engine/core/EntityManager.cpp.s

engine/core/Utils.o: engine/core/Utils.cpp.o

.PHONY : engine/core/Utils.o

# target to build an object file
engine/core/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/Utils.cpp.o
.PHONY : engine/core/Utils.cpp.o

engine/core/Utils.i: engine/core/Utils.cpp.i

.PHONY : engine/core/Utils.i

# target to preprocess a source file
engine/core/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/Utils.cpp.i
.PHONY : engine/core/Utils.cpp.i

engine/core/Utils.s: engine/core/Utils.cpp.s

.PHONY : engine/core/Utils.s

# target to generate assembly for a file
engine/core/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/core/Utils.cpp.s
.PHONY : engine/core/Utils.cpp.s

engine/rendering/IndexBuffer.o: engine/rendering/IndexBuffer.cpp.o

.PHONY : engine/rendering/IndexBuffer.o

# target to build an object file
engine/rendering/IndexBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/IndexBuffer.cpp.o
.PHONY : engine/rendering/IndexBuffer.cpp.o

engine/rendering/IndexBuffer.i: engine/rendering/IndexBuffer.cpp.i

.PHONY : engine/rendering/IndexBuffer.i

# target to preprocess a source file
engine/rendering/IndexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/IndexBuffer.cpp.i
.PHONY : engine/rendering/IndexBuffer.cpp.i

engine/rendering/IndexBuffer.s: engine/rendering/IndexBuffer.cpp.s

.PHONY : engine/rendering/IndexBuffer.s

# target to generate assembly for a file
engine/rendering/IndexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/IndexBuffer.cpp.s
.PHONY : engine/rendering/IndexBuffer.cpp.s

engine/rendering/RenderingManager.o: engine/rendering/RenderingManager.cpp.o

.PHONY : engine/rendering/RenderingManager.o

# target to build an object file
engine/rendering/RenderingManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/RenderingManager.cpp.o
.PHONY : engine/rendering/RenderingManager.cpp.o

engine/rendering/RenderingManager.i: engine/rendering/RenderingManager.cpp.i

.PHONY : engine/rendering/RenderingManager.i

# target to preprocess a source file
engine/rendering/RenderingManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/RenderingManager.cpp.i
.PHONY : engine/rendering/RenderingManager.cpp.i

engine/rendering/RenderingManager.s: engine/rendering/RenderingManager.cpp.s

.PHONY : engine/rendering/RenderingManager.s

# target to generate assembly for a file
engine/rendering/RenderingManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/RenderingManager.cpp.s
.PHONY : engine/rendering/RenderingManager.cpp.s

engine/rendering/Shader.o: engine/rendering/Shader.cpp.o

.PHONY : engine/rendering/Shader.o

# target to build an object file
engine/rendering/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/Shader.cpp.o
.PHONY : engine/rendering/Shader.cpp.o

engine/rendering/Shader.i: engine/rendering/Shader.cpp.i

.PHONY : engine/rendering/Shader.i

# target to preprocess a source file
engine/rendering/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/Shader.cpp.i
.PHONY : engine/rendering/Shader.cpp.i

engine/rendering/Shader.s: engine/rendering/Shader.cpp.s

.PHONY : engine/rendering/Shader.s

# target to generate assembly for a file
engine/rendering/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/Shader.cpp.s
.PHONY : engine/rendering/Shader.cpp.s

engine/rendering/ShaderProgram.o: engine/rendering/ShaderProgram.cpp.o

.PHONY : engine/rendering/ShaderProgram.o

# target to build an object file
engine/rendering/ShaderProgram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/ShaderProgram.cpp.o
.PHONY : engine/rendering/ShaderProgram.cpp.o

engine/rendering/ShaderProgram.i: engine/rendering/ShaderProgram.cpp.i

.PHONY : engine/rendering/ShaderProgram.i

# target to preprocess a source file
engine/rendering/ShaderProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/ShaderProgram.cpp.i
.PHONY : engine/rendering/ShaderProgram.cpp.i

engine/rendering/ShaderProgram.s: engine/rendering/ShaderProgram.cpp.s

.PHONY : engine/rendering/ShaderProgram.s

# target to generate assembly for a file
engine/rendering/ShaderProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/ShaderProgram.cpp.s
.PHONY : engine/rendering/ShaderProgram.cpp.s

engine/rendering/Texture.o: engine/rendering/Texture.cpp.o

.PHONY : engine/rendering/Texture.o

# target to build an object file
engine/rendering/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/Texture.cpp.o
.PHONY : engine/rendering/Texture.cpp.o

engine/rendering/Texture.i: engine/rendering/Texture.cpp.i

.PHONY : engine/rendering/Texture.i

# target to preprocess a source file
engine/rendering/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/Texture.cpp.i
.PHONY : engine/rendering/Texture.cpp.i

engine/rendering/Texture.s: engine/rendering/Texture.cpp.s

.PHONY : engine/rendering/Texture.s

# target to generate assembly for a file
engine/rendering/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/Texture.cpp.s
.PHONY : engine/rendering/Texture.cpp.s

engine/rendering/VertexArray.o: engine/rendering/VertexArray.cpp.o

.PHONY : engine/rendering/VertexArray.o

# target to build an object file
engine/rendering/VertexArray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/VertexArray.cpp.o
.PHONY : engine/rendering/VertexArray.cpp.o

engine/rendering/VertexArray.i: engine/rendering/VertexArray.cpp.i

.PHONY : engine/rendering/VertexArray.i

# target to preprocess a source file
engine/rendering/VertexArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/VertexArray.cpp.i
.PHONY : engine/rendering/VertexArray.cpp.i

engine/rendering/VertexArray.s: engine/rendering/VertexArray.cpp.s

.PHONY : engine/rendering/VertexArray.s

# target to generate assembly for a file
engine/rendering/VertexArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/VertexArray.cpp.s
.PHONY : engine/rendering/VertexArray.cpp.s

engine/rendering/VertexBuffer.o: engine/rendering/VertexBuffer.cpp.o

.PHONY : engine/rendering/VertexBuffer.o

# target to build an object file
engine/rendering/VertexBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/VertexBuffer.cpp.o
.PHONY : engine/rendering/VertexBuffer.cpp.o

engine/rendering/VertexBuffer.i: engine/rendering/VertexBuffer.cpp.i

.PHONY : engine/rendering/VertexBuffer.i

# target to preprocess a source file
engine/rendering/VertexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/VertexBuffer.cpp.i
.PHONY : engine/rendering/VertexBuffer.cpp.i

engine/rendering/VertexBuffer.s: engine/rendering/VertexBuffer.cpp.s

.PHONY : engine/rendering/VertexBuffer.s

# target to generate assembly for a file
engine/rendering/VertexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/VertexBuffer.cpp.s
.PHONY : engine/rendering/VertexBuffer.cpp.s

engine/rendering/VertexBufferLayout.o: engine/rendering/VertexBufferLayout.cpp.o

.PHONY : engine/rendering/VertexBufferLayout.o

# target to build an object file
engine/rendering/VertexBufferLayout.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/VertexBufferLayout.cpp.o
.PHONY : engine/rendering/VertexBufferLayout.cpp.o

engine/rendering/VertexBufferLayout.i: engine/rendering/VertexBufferLayout.cpp.i

.PHONY : engine/rendering/VertexBufferLayout.i

# target to preprocess a source file
engine/rendering/VertexBufferLayout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/VertexBufferLayout.cpp.i
.PHONY : engine/rendering/VertexBufferLayout.cpp.i

engine/rendering/VertexBufferLayout.s: engine/rendering/VertexBufferLayout.cpp.s

.PHONY : engine/rendering/VertexBufferLayout.s

# target to generate assembly for a file
engine/rendering/VertexBufferLayout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/VertexBufferLayout.cpp.s
.PHONY : engine/rendering/VertexBufferLayout.cpp.s

engine/rendering/lib/stb_image/stb_image.o: engine/rendering/lib/stb_image/stb_image.c.o

.PHONY : engine/rendering/lib/stb_image/stb_image.o

# target to build an object file
engine/rendering/lib/stb_image/stb_image.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/lib/stb_image/stb_image.c.o
.PHONY : engine/rendering/lib/stb_image/stb_image.c.o

engine/rendering/lib/stb_image/stb_image.i: engine/rendering/lib/stb_image/stb_image.c.i

.PHONY : engine/rendering/lib/stb_image/stb_image.i

# target to preprocess a source file
engine/rendering/lib/stb_image/stb_image.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/lib/stb_image/stb_image.c.i
.PHONY : engine/rendering/lib/stb_image/stb_image.c.i

engine/rendering/lib/stb_image/stb_image.s: engine/rendering/lib/stb_image/stb_image.c.s

.PHONY : engine/rendering/lib/stb_image/stb_image.s

# target to generate assembly for a file
engine/rendering/lib/stb_image/stb_image.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/engine/rendering/lib/stb_image/stb_image.c.s
.PHONY : engine/rendering/lib/stb_image/stb_image.c.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/main.cpp.s
.PHONY : main.cpp.s

objects/Ball.o: objects/Ball.cpp.o

.PHONY : objects/Ball.o

# target to build an object file
objects/Ball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/Ball.cpp.o
.PHONY : objects/Ball.cpp.o

objects/Ball.i: objects/Ball.cpp.i

.PHONY : objects/Ball.i

# target to preprocess a source file
objects/Ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/Ball.cpp.i
.PHONY : objects/Ball.cpp.i

objects/Ball.s: objects/Ball.cpp.s

.PHONY : objects/Ball.s

# target to generate assembly for a file
objects/Ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/Ball.cpp.s
.PHONY : objects/Ball.cpp.s

objects/Enemy.o: objects/Enemy.cpp.o

.PHONY : objects/Enemy.o

# target to build an object file
objects/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/Enemy.cpp.o
.PHONY : objects/Enemy.cpp.o

objects/Enemy.i: objects/Enemy.cpp.i

.PHONY : objects/Enemy.i

# target to preprocess a source file
objects/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/Enemy.cpp.i
.PHONY : objects/Enemy.cpp.i

objects/Enemy.s: objects/Enemy.cpp.s

.PHONY : objects/Enemy.s

# target to generate assembly for a file
objects/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/Enemy.cpp.s
.PHONY : objects/Enemy.cpp.s

objects/GameObject.o: objects/GameObject.cpp.o

.PHONY : objects/GameObject.o

# target to build an object file
objects/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/GameObject.cpp.o
.PHONY : objects/GameObject.cpp.o

objects/GameObject.i: objects/GameObject.cpp.i

.PHONY : objects/GameObject.i

# target to preprocess a source file
objects/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/GameObject.cpp.i
.PHONY : objects/GameObject.cpp.i

objects/GameObject.s: objects/GameObject.cpp.s

.PHONY : objects/GameObject.s

# target to generate assembly for a file
objects/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/GameObject.cpp.s
.PHONY : objects/GameObject.cpp.s

objects/Player.o: objects/Player.cpp.o

.PHONY : objects/Player.o

# target to build an object file
objects/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/Player.cpp.o
.PHONY : objects/Player.cpp.o

objects/Player.i: objects/Player.cpp.i

.PHONY : objects/Player.i

# target to preprocess a source file
objects/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/Player.cpp.i
.PHONY : objects/Player.cpp.i

objects/Player.s: objects/Player.cpp.s

.PHONY : objects/Player.s

# target to generate assembly for a file
objects/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/objects/Player.cpp.s
.PHONY : objects/Player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... project"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... engine/core/Camera.o"
	@echo "... engine/core/Camera.i"
	@echo "... engine/core/Camera.s"
	@echo "... engine/core/Engine.o"
	@echo "... engine/core/Engine.i"
	@echo "... engine/core/Engine.s"
	@echo "... engine/core/EntityManager.o"
	@echo "... engine/core/EntityManager.i"
	@echo "... engine/core/EntityManager.s"
	@echo "... engine/core/Utils.o"
	@echo "... engine/core/Utils.i"
	@echo "... engine/core/Utils.s"
	@echo "... engine/rendering/IndexBuffer.o"
	@echo "... engine/rendering/IndexBuffer.i"
	@echo "... engine/rendering/IndexBuffer.s"
	@echo "... engine/rendering/RenderingManager.o"
	@echo "... engine/rendering/RenderingManager.i"
	@echo "... engine/rendering/RenderingManager.s"
	@echo "... engine/rendering/Shader.o"
	@echo "... engine/rendering/Shader.i"
	@echo "... engine/rendering/Shader.s"
	@echo "... engine/rendering/ShaderProgram.o"
	@echo "... engine/rendering/ShaderProgram.i"
	@echo "... engine/rendering/ShaderProgram.s"
	@echo "... engine/rendering/Texture.o"
	@echo "... engine/rendering/Texture.i"
	@echo "... engine/rendering/Texture.s"
	@echo "... engine/rendering/VertexArray.o"
	@echo "... engine/rendering/VertexArray.i"
	@echo "... engine/rendering/VertexArray.s"
	@echo "... engine/rendering/VertexBuffer.o"
	@echo "... engine/rendering/VertexBuffer.i"
	@echo "... engine/rendering/VertexBuffer.s"
	@echo "... engine/rendering/VertexBufferLayout.o"
	@echo "... engine/rendering/VertexBufferLayout.i"
	@echo "... engine/rendering/VertexBufferLayout.s"
	@echo "... engine/rendering/lib/stb_image/stb_image.o"
	@echo "... engine/rendering/lib/stb_image/stb_image.i"
	@echo "... engine/rendering/lib/stb_image/stb_image.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... objects/Ball.o"
	@echo "... objects/Ball.i"
	@echo "... objects/Ball.s"
	@echo "... objects/Enemy.o"
	@echo "... objects/Enemy.i"
	@echo "... objects/Enemy.s"
	@echo "... objects/GameObject.o"
	@echo "... objects/GameObject.i"
	@echo "... objects/GameObject.s"
	@echo "... objects/Player.o"
	@echo "... objects/Player.i"
	@echo "... objects/Player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

